# style のルール
style:
  active: true
  #
  # MaximumLineLength
  #
  # 概要
  # - 1行当たりの長さ
  #
  MaxLineLength:
    active: true
    excludes: ['**/test/**'] # (default: なし）
    maxLineLength: 120
    excludePackageStatements: true
    excludeImportStatements: true
    excludeCommentStatements: false
  #
  # UnusedImports
  #
  # 概要
  # - 未使用の import を禁止する
  #
  UnusedImports:
    active: true # (default: false)

# コメントのルール
comments:
  active: true
  #
  # UndocumentedPublicClass
  #
  # 概要
  # - public な class、object、interface にコメントの記述を必須にする
  #
  UndocumentedPublicClass:
    active: true # (default: false)
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    searchInNestedClass: true
    searchInInnerClass: true
    searchInInnerObject: true
    searchInInnerInterface: true
  #
  # UndocumentedPublicFunction
  #
  # 概要
  # - public な関数にコメントの記述を必須にする
  #
  UndocumentedPublicFunction:
    active: true # (default: false)
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
  #
  # UndocumentedPublicProperty
  #
  # 概要
  # - public なプロパティにコメントの記述を必須にする
  #
  UndocumentedPublicProperty:
    active: true # (default: false)
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']

exceptions:
  active: true
  TooGenericExceptionCaught:
    active: true
    excludes: ['**/test/**', '**/androidTest/**', '**/commonTest/**', '**/jvmTest/**', '**/jsTest/**', '**/iosTest/**']
    exceptionNames:
      - 'ArrayIndexOutOfBoundsException'
      # - 'Error' # default（コメントイン）
      # - 'Exception'  # default（コメントイン）
      - 'IllegalMonitorStateException'
      - 'IndexOutOfBoundsException'
      - 'NullPointerException'
      - 'RuntimeException'
      - 'Throwable'

formatting:
  active: true
  android: false
  autoCorrect: true
  #
  # MaximumLineLength
  #
  # 概要
  # - 1行当たりの文字数
  #
  MaximumLineLength:
    active: true
    excludes: ['**/test/**'] # (default: なし）
    maxLineLength: 120
    ignoreBackTickedIdentifier: false
